version: "3.9"
networks:
  outside:

services:
  db:
    container_name: app-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 8002:1433
    networks:
      - outside
  web:
    container_name: itu-minitwit
    image: ${DOCKER_REGISTRY-}itu-minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:80
    networks:
      - outside