version: "3.9"
services:
  web:
    build: ./itu-minitwit/Server
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_HTTP_PORT=https://+:5001
      - ASPNETCORE_URLS=http://+:5000