version: "3.9"
networks:
  outside:

services:
  web:
    container_name: minitwit
    image: minitwit
    build:
      context: .
      dockerfile: Minitwit/Dockerfile
    ports:
      - 8765:7112
    environment:
      - ASPNETCORE_URLS=http://+:7112/
    networks:
      - outside
    