version: "3.9"

services:
  postgresdb:
    image: postgres:latest
    container_name: minitwitdb
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - 2345:5432
    networks:
      - outside
    healthcheck:
      test: "exit 0"
  
  web:
    container_name: minitwitserver
    image: minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8765:7112
    environment:
      - ASPNETCORE_URLS=http://+:7112/
      - DB_HOST=172.17.0.1
      - DB_PASSWORD=postgres
      - DB_PORT=2345
      - IGNORE_ANTIFORGERY_TOKEN=True
    networks:
      - outside
    depends_on:
      postgresdb:
        condition: service_healthy

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - outside

  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"  
    networks:
      - outside  
  
networks:
  outside: