version: "3.9"
networks:
  outside:

services:
  web:
    container_name: itu-minitwit
    image: ${DOCKER_REGISTRY-}itu-minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5108:5108
    environment:
      - ASPNETCORE_URLS=http://+:5108/
    networks:
      - outside
    