version: "3.9"
networks:
  outside:

services:
  web:
    container_name: itu-minitwit
    image: ${DOCKER_REGISTRY-}itu-minitwit
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5108
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - outside