{
 "title": "dash",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "messages created (last 30 min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "minitwit_messages_created_time" }
   ]
  },
  {
   "title": "active users (tweeted last 12h)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "minitwit_active_users{}" }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "dotnet_total_memory_bytes" }
   ]
  }
 ]
}