version: "3.3"

services:
  web:
    container_name: minitwitserver
    image: ${DOCKER_USERNAME}/itu-minitwit-jason
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:7112
    environment:
      - ASPNETCORE_URLS=http://+:7112/
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
    networks:
      - outside

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - outside

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"  
    networks:
      - outside  
      
networks:
  outside: