version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: minitwitdb
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - outside
    healthcheck:
      test: "exit 0"
  
  web:
    container_name: minitwitserver
    image: ${DOCKER_USERNAME}/itu-minitwit-jason
    ports:
      - 8765:7112
    environment:
      - ASPNETCORE_URLS=http://+:7112/
      - DB_HOST=db
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      - DB_USER=postgres
      - LOKI_HOST=loki
    networks:
      - outside
    deploy:
      mode: global

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.swarm.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - outside
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    networks:
      - outside
    deploy:
      placement:
        constraints:
          - node.role == manager
  
  loki:
    image: grafana/loki:2.7.3
    ports:
      - target: 3100
        published: 3100
        protocol: tcp
        mode: ingress
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - /minitwit/data/loki/config.yaml:/etc/loki/config.yaml
    networks:
      - outside
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  outside:
    driver: overlay

# docker stack deploy -c docker-compose.swarm.yml ministack
