version: "3.3"

services:
  web:
    image: ${DOCKER_USERNAME}/itu-minitwit-jason
    container_name: minitwitserver
    ports:
      - 8765:7112
    environment:
      - ASPNETCORE_URLS=http://+:7112/
      - DB_HOST=${DB_HOST}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - LOKI_HOST=172.17.0.1
    networks:
      - outside

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - outside

  grafana:
    image: grafana/grafana:8.2.6
    ports:
      - "3000:3000"  
    networks:
      - outside 
  
  loki:
    image: grafana/loki:2.7.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - outside

networks:
  outside:
    
# docker stack deploy -c docker-compose.yml ministack
# TODO make network overlay and replace 172.17.0.1 here and in prometheus.yml