version: "3.3"

volumes:
  elk_elasticsearch_data:
    
networks:
  logging:

services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.1"
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms700m -Xmx1g"
      - "discovery.type=single-node"
    volumes:
      - elk_elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - logging

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.17.1"
    ports:
      - "5601:5601"
    environment:
      elasticsearch.hosts: '["http://elasticsearch:9200"]'
    networks:
      - logging