name: Report
on:
  push:
    branches:
      - main
      - master
    paths:
      - 'report/**'
  workflow_dispatch:

jobs:
  build-report:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Git repo setup
        uses: actions/checkout@v2
      - name: Compile LaTex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main.tex
          working_directory: report
      - name: move pdf
        run: |
          mkdir -p build
          mv main.pdf build/report.pdf
        working-directory: report
        
      - name: Publish LaTex
        run: |
          git config --global user.email "madspiriwe99@gmail.com"
          git config --global user.name "Stalin1999"
          git add -f $PWD/report/build/*.pdf
          git commit -m "Workflow - Update report PDF"
          git push --force
